[project]
name = "fembot"
version = "0.1.0"
description = "The cutest discord bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "davey>=0.1.6",
    "discord-py>=2.7.1",
    "dotenv>=0.9.9",
    "pynacl>=1.6.2",
]

[project.scripts]
fembot = "fembot:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
